steps:
  - label: ":parcel: Build"
    command:
      - ./.buildkite/setup.sh
      - yarn build --cache-dir $PARCEL_CACHE_PATH
    plugins:
      - git-clean#v0.0.1:
          flags: "-fdqx --exclude=node_modules"
