steps:
  - label: ":buildkite: Debug"
    command:
      - ls $BUILDKITE_BUILD_CHECKOUT_PATH
  - label: ":parcel: Build"
    command:
      - ls $BUILDKITE_BUILD_CHECKOUT_PATH
      - ls /workdir
      - yarn build
    plugins:
      - docker#v1.1.1:
          image: "node:10"
          workdir: "$BUILDKITE_BUILD_CHECKOUT_PATH"
          volumes:
            - "$BUILDKITE_BUILD_CHECKOUT_PATH:$BUILDKITE_BUILD_CHECKOUT_PATH"
