steps:
  - label: ":buildkite: Debug"
    command:
      - ls
      - pwd
      - ls /
      - ls /buildkite
      - ls /home
  - label: ":parcel: Build"
    command:
      - ls
      - pwd
      - ls /
      - ls /home
    plugins:
      - docker#v1.1.1:
          image: "node:10"
