steps:
  - label: ":buildkite: Debug"
    command:
      - ls
      - pwd
      - ls /
      - ls /buildkite/builds
      - ls /home
      - ls /home/builds
  - label: ":parcel: Build"
    command:
      - ls
      - pwd
      - ls /
      - ls /home
    plugins:
      - docker#v1.1.1:
          image: "node:10"
          volumes:
            - "$BUILDKITE_BUILD_CHECKOUT_PATH:/workdir"
